release_path: "https://github.com/superseriousbusiness/gotosocial/releases/download/v{{ release_version }}"
release_file: "gotosocial_{{ release_version }}_linux_amd64.tar.gz"
binary_path: "{{ deploy_dir }}/gotosocial"
default_config_entries:
  storage-local-base-bath: "{{ deploy_dir }}/storage"
  letsencrypt-cert-dir: "{{ deploy_dir }}/storage/certs"
  log-client-ip: false
  letsencrypt-enabled: true
  accounts-registration-open: false
  port: 443
  db-type: sqlite
  db-address: sqlite.db

merged_config_entries: "{{ default_config_entries | combine(config_entries|default({})) }}"
