- hosts: gotosocial
  become: true
  vars_files:
    - vars/defaults.yaml
  vars:
    sqlite_file_path: "{{ merged_config_entries['db-address'] }}"
  tasks:
    - tags: print_action
      service: name=gotosocial state=stopped

    - block:
      - name: download database files
        tags: print_action
        fetch:
          src: "{{ deploy_dir }}/{{ item.file }}"
          dest: "{{ local_dir }}/backup/{{ item.file }}"
          flat: yes
          fail_on_missing: "{{ item.fail_on_missing }}"
        loop:
          - file: "{{ sqlite_file_path }}"
            fail_on_missing: yes
        become: false

      - name: archive storage/ directory
        tags: print_action
        archive:
          path: "{{ deploy_dir }}/storage"
          dest: "{{ deploy_dir }}/storage.tgz"

      - name: download storage archive
        tags: print_action
        fetch:
          src: "{{ deploy_dir }}/storage.tgz"
          dest: "{{ local_dir }}/backup/storage.tgz"
          flat: yes
        become: false

      - name: remove storage archive
        file:
          path: "{{ deploy_dir }}/storage.tgz"
          state: absent

      always:
      - tags: print_action
        service: name=gotosocial state=started
