- hosts: gotosocial
  become: true
  vars_files:
    - vars/defaults.yaml
  tasks:
    - include_tasks: tasks/check-vars.yaml

    - include_tasks: tasks/download-and-verify.yaml

    - when: ansible_selinux.status == "enabled"
      block:
        - when: ansible_os_family == "RedHat"
          package:
            name: policycoreutils-python-utils
            state: present

        - name: "SELinux label binary path {{ binary_path }}"
          tags: print_action
          when: ansible_os_family == "RedHat"
          sefcontext:
            target: "{{ binary_path }}"
            setype: bin_t
            state: present

    - name: create gotosocial user
      tags: print_action
      user:
        name: gotosocial
        state: present
        create_home: false

    - include_tasks: tasks/upload-and-unpack.yaml

    - include_tasks: tasks/config-and-service.yaml

    - name: start gotosocial
      tags: print_action
      service:
        name: gotosocial
        state: started
        enabled: yes
      register: started

    - name: restart gotosocial
      tags: print_action
      service:
        name: gotosocial
        state: restarted
      when: not started.changed
